language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "pip install -r https://raw.githubusercontent.com/wazo-pbx/wazo-admin-ui/master/requirements.txt"
  - "python setup.py install"
script: nosetests user
notifications:
  email:
    recipients:
      - dev+tests-reports@wazo.community
    on_success: change
    on_failure: change
branches:
  only:
    - master
sudo: false
