sync:
  image: n3llyb0y/wait
  links:
    - admin-ui
    - auth
    - confd
    - browser
    - postgres
    - provd
    - rabbitmq
    - sysconfd
  environment:
    PORTS: "4444 5432 5672 8666 8668 9296 9486 9497"
    TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

admin-ui:
  image: wazo-admin-ui-user-test
  ports:
    - "9296"
  links:
    - confd
    - auth
  volumes:
    - "../../..:/usr/src/wazo-admin-ui-user"
    - "./etc/wazo-admin-ui:/etc/wazo-admin-ui"
    - "./ssl:/usr/local/share/ssl"

auth:
  image: wazopbx/xivo-auth-mock
  expose:
    - "9497"

confd:
  image: wazopbx/xivo-confd
  ports:
    - "9486"
  links:
    - auth
    - postgres
    - provd
    - rabbitmq
    - sysconfd
  volumes:
    - "./etc/xivo-confd:/etc/xivo-confd"

browser:
  image: selenium/standalone-firefox
  ports:
    - "4444"
  links:
    - admin-ui

postgres:
  image: wazopbx/postgres-test
  expose:
    - "5432"

provd:
  image: wazopbx/xivo-provd
  ports:
    - "8666"
  volumes:
    - "./etc/xivo-provd/provd.conf:/etc/xivo/provd/provd.conf"

rabbitmq:
  image: rabbitmq
  expose:
    - "5672"

sysconfd:
  image: p0bailey/docker-flask
  expose:
    - "8668"
  volumes:
    - "./mocks/sysconfd.py:/tmp/sysconfd.py"
  command: "python /tmp/sysconfd.py"
