name: admin-ui-user
namespace: official
version: 1.1.0
author: Wazo Team
display_name: User
min_wazo_version: 17.17
tags:
  - beta
  - users
homepage: https://github.com/wazo-pbx/wazo-admin-ui-user
depends:
  - name: admin-ui-context
    namespace: official
    version: 1.0.1
  - name: admin-ui-extension
    namespace: official
    version: 1.2.0
  - name: admin-ui-device
    namespace: official
