name: admin-ui-user
namespace: official
version: 1.5.0-1
author: Wazo Team
display_name: User
min_wazo_version: 18.04
tags:
  - users
homepage: https://github.com/wazo-pbx/wazo-admin-ui-user
icon: user
depends:
  - name: admin-ui-context
    namespace: official
  - name: admin-ui-extension
    namespace: official
  - name: admin-ui-device
    namespace: official
  - name: admin-ui-funckey
    namespace: official
  - name: admin-ui-schedule
    namespace: official
  - name: admin-ui-voicemail
    namespace: official
